---
title: "Draft timeline for Colorado hiking trip, 3rd weekend, Aug., 2016"
author: "M. Terry"
date: "July 16, 2016"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# A Goal

**No injuries**

# Timeline

### *Wed, Aug 15*

Plan pick up John's hiking equipment between 4 & 5 pm. 

### *Wed, Aug 17*

M. Terry drive Lincoln to Ogallala, visit wi classmates, with D. Pierce, couple

other classmates, 6pm, Open Range Grill.

### *Thurs, Aug 18*

M. Terry drive Ogallala to Fort Collins, arrive around noon, prepare for Friday. Include

trip to REI store, complete Charles checklist for hiking.

### *Fri, Aug 19*

Be packed, ready for trip to Wilswood.

10:00am, L. Callen, Charles

Charles made sure Wildwood knows we plan possible 'late arrival' (after 5pm). They will 

arrange 'late arrival packet'.

Charles, M. Terry check if any problem with rough roads getting to peak we decide 

to hike on.

Wildwood Suites address/info.

120 Sawmill Road

Breckenridge, Colorado

Toll Free 800.866.0300

Front Desk 970.453.0232

M. Terry, C. Smith arrive at Wildwood Suites at ??pm

J. Terry arrives DIA, 5:05pm, rents vehicle, drives to Wildwood Suites. ETA: ~ 8pm ???????

### *Sat, Aug 20*

--breakfast (M. Terry, others if like): Charles indicates Wildwood has a little refrig. in room.

I can get milk, & bring banana, peach, raisin brand, plastic bowl, plastic utensils, 

& paper towel roll (my usual breakfast). Also, apple & orange.


Hike location: 14teeners, Torrey & Gray, tho Charles still considering alternative.

Time leave Wildwood for hiking = ??am. C. Smith indicates need begin hiking by 7:00am, 

be going down Grays by 12:30pm.

### *Sun, Aug 21*

Wildwood checkout time: 10am.

Vail: (from 07/30/16 C. Smith email), C. Smith suggests could go to Vail, do gondola,

check out the top ???????

J. Terry drives to DIA for flight departing 5:10pm

C. Smith, M. Terry follow suggestion C. Smith, more Vail, Glenwood springs, Hanging Lake?

### *Mon, Aug 22*

M. Terry, potentially check out bikeFriday, Boulder.

Later drive to Ogallala, possibly stay overnite.

### *Tues, Aug 23*

M. Terry, drive Ogallala to lincoln, like be back Lincoln on Tues., 4pm.


